### ISSUE TITLE
Windows maximize when dragged to top

### ISSUE THREAD

**Issue by IvanRF** [kirill-grouchnikov/substance#73]
### Version of Substance
8.0-dev

### Version of Java
8 update 144

### Version of OS
Win 10

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

Always had this doubt, why window maximize when dragged to top does not work? Is it a Java issue or can be addressed at the Look and Feel level?

Expected (`com.sun.java.swing.plaf.windows.WindowsLookAndFeel`)
![ezgif-5-5b8f12c2ce](https://user-images.githubusercontent.com/6751650/35869197-463a7c6c-0b3d-11e8-92e7-54a83cb578b7.gif)

Actual: nothing happens when dragged to top with Substance or `MetalLookAndFeel`, for example.

**Comment by kirill-grouchnikov** [comment]
As far as I know, you get this from the OS level for windows that have native decorations. Different versions of Windows (Vista, 7, 10) have different behaviors of what happens when you drag and let go along different edges / corners.

I do not have any plans to recreate that functionality in Substance. That is either for native window manager or for the individual app to do if they desire to do so.
