### ISSUE TITLE
Colorize SVG icons on skin change

### ISSUE THREAD

**Issue by IvanRF** [kirill-grouchnikov/substance#91]
I'm trying to move to material design, based on version 8.0 icons. I used the Ibis project and created all the Java files, like the ones on [org/pushingpixels/substance/internal/svg](https://github.com/kirill-grouchnikov/substance/tree/master/src/org/pushingpixels/substance/internal/svg).

If I change the Substance skin on runtime, I can see that context menu icons change too and maintain the color scheme of the selected skin. However, all the icons in existing `JButton`s defined by the application remain with the older color.

Which will be the best approach in order to update all the icons colors for the components that were created before an skin change?

I saw that `SubstanceIconUIResource.colorize(Color)` is used in places like [SubstanceDefaultIconPack.java#L277](https://github.com/kirill-grouchnikov/substance/blob/master/src/org/pushingpixels/substance/api/icon/SubstanceDefaultIconPack.java#L277).

As an idea, do you think it could be possible to create a way that a `SubstanceIcon` or `SubstanceIconUIResource` always update the colorization if the skin is changed?

**Comment by kirill-grouchnikov** [comment]
Text field context menu content is created every single time that menu is shown. You can see that in EditContextMenuWidget and the icon colorization through the icon pack in the get*Item() calls. Those are all done at runtime since it's a rather infrequently used functionality that is acceptable to have a bit of an overhead.

I would suggest looking at SubstanceCortex.GlobalScope.setUseThemedDefaultIcons API which seems like a close fit for what you're looking for. If you're using simple monochrome icons then using that API should be colorizing the icons based on the current skin. The downside might be for dark themes where the active icon (in rollover etc states) would be using the original colors.

In general, icon colorization is expensive to do dynamically every time an icon is painted. Internally in Substance's default icon pack it is done by calling SubstanceIconUIResource.colorize - which is a supported Substance APIs. Under the hood it uses Java2D filtering APIs to effectively apply a certain filter on the entire image. That is expensive depending on how big the image is and how many images you want to do this for. Due to this, there is a lot of image caching going on in Substance.

GlobalCortex.registerSkinChangeListener can be used to register a listener to be invoked when Substance skin is changed. There you can make a pass over the entire UI and update all the icons in your app depending on the visuals you want to achieve.

I don't see Substance being in the business of tracking all application icons / controls and calling the application code back to update all of those when a skin changes. That is a huge potential for memory leaks that I'm not quite willing to take on.

**Comment by IvanRF** [comment]
> I would suggest looking at SubstanceCortex.GlobalScope.setUseThemedDefaultIcons API which seems like a close fit for what you're looking for.

Excellent! that API does the trick 👍 

I can see the icons changing the colorization when moving from Gemini to Magellan, for example.

![gemini](https://user-images.githubusercontent.com/6751650/40012114-0dc6e282-5780-11e8-9830-3fd338d1dc4f.png)     ![magellan](https://user-images.githubusercontent.com/6751650/40012123-1273a7d4-5780-11e8-9da2-459324624531.png)
